DATA_PATH: 'data'
MODEL_OUT: 'out'

MACHINE:
  NAME: 'test'

TRAIN:
- SENSOR_NAME: 'aro_vib1'
  SEQ_LEN: 3
  LATENT_DIM: 64
  LEARNING_RATE: 0.001
  EPOCH: 3
  BATCH_SIZE: 150
  THRESHOLD: 1
- SENSOR_NAME: 'aro_vib2'
  SEQ_LEN: 3
  LATENT_DIM: 64
  LEARNING_RATE: 0.001
  EPOCH: 3
  BATCH_SIZE: 150
  THRESHOLD: 1